# Configuration for human counting


human_count:
  # Increasing the value makes the output more stable but the response is slower
  smoothness: 10

  # Text position
  position: [20, 80]

  # Save output
  save: true
