# Configuration for train.py


# Set global seed
set_seed: 42

# Set number of workers (int | float)
num_workers: 0.6

# Config dataset
data:
  data_path: data/processed/custom_x
  augment_level: 0
  image_size: [224, 224]

# Config model
model:
  pretrained: true
  freeze: false

# Config scheduler
scheduler:
  warmup_epochs: 10
  start_factor: 0.01

# Config trainer
trainer:
  batch_size: 156
  learning_rate: 1e-6
  num_epoch: 100
  checkpoint: null
  precision: 16-mixed
